// This file is generated by scripts/generate-topic-registries.cjs. Do not edit manually.
import type { Topic } from "@/components/topics/types";
import Topic0, { metadata as metadata0 } from "./topics/pressures-and-change";

export const topics = [
  { ...metadata0, Component: Topic0 } satisfies Topic,
].sort(
  (left, right) =>
    left.order - right.order || left.title.localeCompare(right.title),
);
