/** @type {import("prettier").Config} */
module.exports = {
  tabWidth: 2,
  printWidth: 80,
  semi: true,
  singleQuote: false,
  jsxSingleQuote: false,
  trailingComma: "all",
  arrowParens: "always",
  importOrder: [
    "^(react/(.*)$)|^(react$)",
    "^(next/(.*)$)|^(next$)",
    "<THIRD_PARTY_MODULES>",
    "",
    "^@/env/(.*)$",
    "^@/types/(.*)$",
    "^@/lib/(.*)$",
    "^@/components/(.*)$",
    "^@/src/(.*)$",
    "^@/app/(.*)$",
    "^@/styles/(.*)$",
    "^@/public/(.*)$",
    "^@/assets/(.*)$",
    "^[./]",
  ],
  importOrderSeparation: false,
  importOrderSortSpecifiers: true,
  importOrderBuiltinModulesToTop: true,
  importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
  importOrderMergeDuplicateImports: true,
  importOrderCombineTypeAndValueImports: true,
  plugins: [
    require.resolve("prettier-plugin-tailwindcss"),
    require.resolve("@ianvs/prettier-plugin-sort-imports"),
  ],
};
