// This file is generated by scripts/generate-topic-registries.cjs. Do not edit manually.
import type { Topic } from "@/components/topics/types";
import Topic0, { metadata as metadata0 } from "./topics/courses";
import Topic1, { metadata as metadata1 } from "./topics/geographic-indications";
import Topic2, {
  metadata as metadata2,
} from "./topics/participatory-approaches";

export const topics = [
  { ...metadata0, Component: Topic0 } satisfies Topic,
  { ...metadata1, Component: Topic1 } satisfies Topic,
  { ...metadata2, Component: Topic2 } satisfies Topic,
].sort(
  (left, right) =>
    left.order - right.order || left.title.localeCompare(right.title),
);
