// This file is generated by scripts/generate-adaptation-topics.cjs. Do not edit manually.
import type { ComponentType } from "react";

import Topic0, {
  metadata as metadata0,
} from "./topics/ecosystem-based-adaptation";
import Topic1, { metadata as metadata1 } from "./topics/pilot-experiences";

export type AdaptationTopicMetadata = {
  slug: string;
  title: string;
  description: string;
  order: number;
};

export type AdaptationTopic = AdaptationTopicMetadata & {
  Component: ComponentType;
};

export const adaptationTopics = [
  { ...metadata0, Component: Topic0 } satisfies AdaptationTopic,
  { ...metadata1, Component: Topic1 } satisfies AdaptationTopic,
].sort(
  (left, right) =>
    left.order - right.order || left.title.localeCompare(right.title),
);
