import Link from "next/link";

import styles from "@/styles/Home.module.css";

export default function AboutData() {
  return (
    <main className={styles.staticContentBox}>
      <Link href="/" className={styles.backLink}>
        <span className={`${styles.arrow} ${styles.left}`}></span>
        back to map
      </Link>



      <h1>About the data</h1>
      <p>
        The Winemap is based on a collection and harmonization of data from
        different sources. Information on the individual PDO regions was
        collected from official legal regulations which can be accessed via the{" "}
        <a
          target="_blank"
          rel="noreferrer"
          style={{ textDecoration: "underline" }}
          href="https://ec.europa.eu/info/food-farming-fisheries/food-safety-and-quality/certification/quality-labels/geographical-indications-register/"
        >
          eAmbrosia database
        </a>
        . This data includes information on geographic boundaries as well as on
        several production regulations, such as authorized grape varieties and
        wine types, maximum yields, and planting density for each PDO region.
        Further details can be found in the corresponding scientific
        publication:
      </p>
      <p>
        <i>
          A geospatial inventory of regulatory information for wine protected
          designations of origin in Europe,- Scientific Data Volume 9, Article
          number: 394 (2022).
        </i>{" "}
        <a
          target="_blank"
          rel="noreferrer"
          href="https://doi.org/10.1038/s41597-022-01513-0"
          style={{ textDecoration: "underline" }}
        >
          https://doi.org/10.1038/s41597-022-01513-0
        </a>
      </p>
      <p>
        To show the extent of vine cultivation within individual PDO regions,
        the Winemap also contains information on the location of vineyards
        throughout Europe. This data was generated by combining information on
        vineyard locations from{" "}
        <a
          target="_blank"
          rel="noreferrer"
          href="https://land.copernicus.eu/pan-european/corine-land-cover"
          style={{ textDecoration: "underline" }}
        >
          Corine Land Cover
        </a>{" "}
        and{" "}
        <a
          target="_blank"
          rel="noreferrer"
          href="https://download.geofabrik.de/"
          style={{ textDecoration: "underline" }}
        >
          OpenStreetMap data
        </a>
        . Combining both data sources allowed us to get the most comprehensive
        overview of vineyard locations in Europe, based on freely accessible
        datasets. However, there are still areas and regions where not all
        vineyards were recorded in our dataset. For details on coverage and
        extent, please refer to individual sources.
      </p>
    </main>
  );
}
